name: build-pdf

on:
  workflow_dispatch: {}
  push:
    paths:
      - "**.tex"
      - "**.bib"
      - "**.sty"
      - "**.cls"
      - ".github/workflows/build-pdf.yml"
      - "Makefile"

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # TeX Live with needed packages (LuaLaTeX stack)
      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: >-
            scheme-medium
            latexmk
            lualatex
            luatex
            fontspec
            unicode-math
            libertinus-fonts
            amsmath
            amssymb
            mathtools
            microtype
            geometry
            titlesec
            titling
            fancyhdr
            lastpage
            hyperref
            bookmark
            graphics
            xcolor
            pgf
            tikz
            siunitx
            enumitem
            booktabs
            longtable
            listings
            physics
            csquotes

      - name: Build (camera-ready)
        run: |
          set -e
          FILE="Lumina_Whitebook_v1.0_ConservationAsIdentity.tex"
          latexmk -lualatex -halt-on-error -interaction=nonstopmode -file-line-error "$FILE"
          mkdir -p public
          cp "${FILE%.tex}.pdf" public/

      - name: Upload artifact (for manual download)
        uses: actions/upload-artifact@v4
        with:
          name: whitebook-pdf
          path: public/*.pdf

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
