name: link-check
on: [push, workflow_dispatch]
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --max-concurrency 8 --retry-wait-time 3 --timeout 20s "**/*.html"
